# Generated by Django 5.0 on 2024-01-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('status', models.CharField(choices=[('o', 'Open'), ('c', 'Close')], default='o', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField(verbose_name='Номер комнаты')),
                ('cost_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='photos_rooms', verbose_name='Фото номера')),
            ],
            options={
                'verbose_name': 'Комната',
                'verbose_name_plural': 'Комнаты',
                'ordering': ['room_number'],
            },
        ),
        migrations.CreateModel(
            name='TypeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип комнаты',
                'verbose_name_plural': 'Типы комнат',
            },
        ),
    ]
