# Generated by Django 5.0 on 2023-12-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
    ]
