# Generated by Django 5.0 on 2024-01-03 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gostinica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gostinica.room'),
        ),
        migrations.AddField(
            model_name='room',
            name='typeroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gostinica.typeroom', verbose_name='Тип номера'),
        ),
    ]
