# Generated by Django 5.0 on 2023-12-18 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostinica', '0002_typeroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='typeroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gostinica.typeroom'),
        ),
    ]
