# Generated by Django 5.0 on 2024-01-05 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostinica', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build_obj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название объекта')),
                ('address', models.CharField(max_length=50, verbose_name='Адрес объекта')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Обьекты',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='build',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gostinica.build_obj', verbose_name='Объект'),
        ),
    ]
