# Generated by Django 5.0 on 2023-12-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gostinica', '0003_room_typeroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
    ]
