# Generated by Django 5.0 on 2023-12-18 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostinica', '0004_remove_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='cost_night',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.IntegerField(verbose_name='Номер комнаты'),
        ),
        migrations.AlterField(
            model_name='room',
            name='typeroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gostinica.typeroom', verbose_name='Тип номера'),
        ),
        migrations.AlterField(
            model_name='typeroom',
            name='title',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
    ]
