# Generated by Django 5.0 on 2023-12-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gostinica', '0005_alter_room_cost_night_alter_room_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
    ]
