# Generated by Django 5.0 on 2023-12-22 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gostinica', '0006_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeroom',
            options={'verbose_name': 'Тип комнаты', 'verbose_name_plural': 'Типы комнат'},
        ),
        migrations.AddField(
            model_name='room',
            name='photo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos_rooms', verbose_name='Фото номера'),
        ),
    ]
